# Generated by Django 4.2.7 on 2026-04-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'completed'])), fields=('user', 'session'), name='unique_active_booking_per_user_session'),
        ),
    ]
